### ISSUE TITLE
ComboBox not showing item list

### ISSUE THREAD

**Issue by cbmlody** [Zesix/Impulse#10]
**Unity ver. 2017.3.1f1**
---
After placing `ComboBoxControlelr` on Canvas, `ComboBoxItemList` script does not expose `object` array.
`StyledComboBox` script is also not creating list items, even after you change objects to strings.

**Comment by Zesix** [comment]
Hi, cbmlody, thanks for opening this issue. The ComboBox was actually added back in Unity 4.6 before they added Dropdown as an actual UI element. The ComboBox was my version of a Dropdown. 

Now that Dropdown is an actual UGUI element, I recommend using that instead of ComboBox. It's a good thing you opened this issue though - I need to remove the ComboBox code that doesn't work anymore.

**Comment by Zesix** [comment]
I've removed the ComboBox code in the latest commit to master. Use the UI Dropdown component instead.
